name: CI/CD Pipeline

on: [push]

jobs:
  # ==========================================
  # JOB 1 : QUALITÉ & SECRETS
  # ==========================================
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Scan des secrets en clair dans le code
      - name: Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run Pytest
        run: pytest test_app.py

  # ==========================================
  # JOB 2 : SÉCURITÉ DE L'IMAGE (Dépend de quality)
  # ==========================================
  security:
    needs: quality 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build local Docker Image for scanning
        run: docker build -t flask-app:local .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-app:local'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  # ==========================================
  # JOB 3 : DÉPLOIEMENT NGROK (Dépend de security)
  # ==========================================
  deploy-tunnel:
    needs: security 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flask-app .

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name my-running-app flask-app

      - name: Test de provocation (Secret Masking)
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: echo "Mon token Ngrok est $NGROK_AUTHTOKEN"

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com/ buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      - name: Open Ngrok Tunnel and Expose App
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          ngrok config add-authtoken $NGROK_AUTHTOKEN
          ngrok http 5000 > /dev/null &
          sleep 5 
          PUBLIC_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          echo "=========================================================="
          echo " L'APPLICATION FLASK EST ACCESSIBLE PUBLIQUEMENT ICI :"
          echo " $PUBLIC_URL"
          echo "=========================================================="
          
          sleep 120

      - name: Clean up resources
        if: always()
        run: |
          docker stop my-running-app || true
          pkill ngrok || true